- name: Install web servers
  hosts: vms
  become: true
  tasks:
    - name: Ensure apache is Present
      ansible.builtin.yum:
        name: httpd
        state: present
- name: Install db servers
  hosts: vms
  become: true
  tasks:
    - name: Ensure postgresql is Present
      ansible.builtin.dnf:
        name:
          - postgresql15.x86_64
          - postgresql15-server
        state: present
    - name: Initialize the PostgreSQL database
      ansible.builtin.command:
        cmd: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION
      register: initdb_result
      changed_when: "'Data directory initialized' in initdb_result.stdout"
    - name: Ensure that postgresql is started
      ansible.builtin.service:
        name: postgresql
        state: started
